# Generated by Django 5.1.1 on 2024-10-15 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('first_release_date', models.DateField()),
                ('last_release_date', models.DateField()),
                ('total_number_of_games', models.IntegerField()),
                ('genre', models.CharField(max_length=200)),
                ('developer', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=200)),
                ('time_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='', verbose_name='')),
                ('release_year', models.IntegerField()),
                ('time_to_beat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('genre', models.CharField(max_length=200)),
                ('series_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todogamesapp.gameseries')),
            ],
        ),
    ]
