# Generated by Django 5.1.1 on 2024-12-05 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todogamesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('started_date', models.DateField()),
                ('completed_date', models.DateField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todogamesapp.game')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todogamesapp.user')),
            ],
        ),
    ]
